name: Job summaries
on: workflow_dispatch
jobs:
  log:
   runs-on: ubuntu-latest
   steps:
    - run: | # マークダウンテキストをジョブサマリーへ出力
        echo "## Example Title :roket:" >> "${GITHUB_STEP_SUMMARY}"
        echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
        echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

      